[package]
name = "day04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
reformation = "0.5.3"
serde_scan = "0.4.1"
vectrix = "0.2.0"